/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicoRouteImport } from './routes/publico'
import { Route as ParticiparRouteImport } from './routes/participar'
import { Route as ParticipanteRouteImport } from './routes/participante'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminParticipantesRouteImport } from './routes/admin_.participantes'
import { Route as AdminMatchesRouteImport } from './routes/admin_.matches'

const PublicoRoute = PublicoRouteImport.update({
  id: '/publico',
  path: '/publico',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticiparRoute = ParticiparRouteImport.update({
  id: '/participar',
  path: '/participar',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipanteRoute = ParticipanteRouteImport.update({
  id: '/participante',
  path: '/participante',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParticipantesRoute = AdminParticipantesRouteImport.update({
  id: '/admin_/participantes',
  path: '/admin/participantes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMatchesRoute = AdminMatchesRouteImport.update({
  id: '/admin_/matches',
  path: '/admin/matches',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/equipe': typeof EquipeRoute
  '/participante': typeof ParticipanteRoute
  '/participar': typeof ParticiparRoute
  '/publico': typeof PublicoRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/participantes': typeof AdminParticipantesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/equipe': typeof EquipeRoute
  '/participante': typeof ParticipanteRoute
  '/participar': typeof ParticiparRoute
  '/publico': typeof PublicoRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/participantes': typeof AdminParticipantesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/equipe': typeof EquipeRoute
  '/participante': typeof ParticipanteRoute
  '/participar': typeof ParticiparRoute
  '/publico': typeof PublicoRoute
  '/admin_/matches': typeof AdminMatchesRoute
  '/admin_/participantes': typeof AdminParticipantesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/como-funciona'
    | '/equipe'
    | '/participante'
    | '/participar'
    | '/publico'
    | '/admin/matches'
    | '/admin/participantes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/como-funciona'
    | '/equipe'
    | '/participante'
    | '/participar'
    | '/publico'
    | '/admin/matches'
    | '/admin/participantes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/como-funciona'
    | '/equipe'
    | '/participante'
    | '/participar'
    | '/publico'
    | '/admin_/matches'
    | '/admin_/participantes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  EquipeRoute: typeof EquipeRoute
  ParticipanteRoute: typeof ParticipanteRoute
  ParticiparRoute: typeof ParticiparRoute
  PublicoRoute: typeof PublicoRoute
  AdminMatchesRoute: typeof AdminMatchesRoute
  AdminParticipantesRoute: typeof AdminParticipantesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/publico': {
      id: '/publico'
      path: '/publico'
      fullPath: '/publico'
      preLoaderRoute: typeof PublicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participar': {
      id: '/participar'
      path: '/participar'
      fullPath: '/participar'
      preLoaderRoute: typeof ParticiparRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participante': {
      id: '/participante'
      path: '/participante'
      fullPath: '/participante'
      preLoaderRoute: typeof ParticipanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/participantes': {
      id: '/admin_/participantes'
      path: '/admin/participantes'
      fullPath: '/admin/participantes'
      preLoaderRoute: typeof AdminParticipantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/matches': {
      id: '/admin_/matches'
      path: '/admin/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AdminMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  EquipeRoute: EquipeRoute,
  ParticipanteRoute: ParticipanteRoute,
  ParticiparRoute: ParticiparRoute,
  PublicoRoute: PublicoRoute,
  AdminMatchesRoute: AdminMatchesRoute,
  AdminParticipantesRoute: AdminParticipantesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
